Purpose: URL is Legitimate or Phising?

In [83]:
#Import necessary libraries with aliases
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [84]:
df = pd.read_csv("PhiUSIIL_Phishing_URL_Dataset.csv")

Firstly, To understand what a dataset is, we first need to understand what columns mean. For this purpose, we created the following dictionary table.

In [85]:
df_data_dict = pd.read_csv("column_explanations.csv")

# Column Explanations as Data Dictionary
data_dict = pd.DataFrame(df.dtypes, columns=['Data Type'])

# Column names
data_dict = data_dict.reset_index().rename(columns={'index': 'Feature Name'})

# 3. First rows values for each column as an example of the values
data_dict['Example'] = df.iloc[0].values

# Explanations from csv file
data_dict['Explanation'] = df_data_dict['english_description']

# Display table
display(data_dict)

,Feature Name,Data Type,Example,Explanation
0,FILENAME,object,521848.txt,Name of the file (can be ignored).
1,URL,object,https://www.southbankmosaics.com,The full URL being analyzed.
2,URLLength,int64,31,Total character length of the URL.
3,Domain,object,www.southbankmosaics.com,"The domain name (e.g., google.com)."
4,DomainLength,int64,24,Character length of the domain name.
5,IsDomainIP,int64,0,Checks if the domain is an IP address (0/1).
6,TLD,object,com,"Top-Level Domain (e.g., .com, .net, .org)."
7,URLSimilarityIndex,float64,100.0,Similarity index with known legitimate sites.
8,CharContinuationRate,float64,1.0,Rate of continuing characters (pattern repetit...
9,TLDLegitimateProb,float64,0.522907,Probability of the TLD being legitimate.
10,URLCharProb,float64,0.061933,Probability distribution of characters in the ...
11,TLDLength,int64,3,Character length of the Top-Level Domain.
12,NoOfSubDomain,int64,1,Number of subdomains present in the URL.
13,HasObfuscation,int64,0,Indicates if obfuscation techniques are used (...
14,NoOfObfuscatedChar,int64,0,Number of obfuscated (hidden/mixed) characters.
15,ObfuscationRatio,float64,0.0,Ratio of obfuscated characters to total length.
16,NoOfLettersInURL,int64,18,Total count of letters in the URL.
17,LetterRatioInURL,float64,0.581,Ratio of letters in the URL.
18,NoOfDegitsInURL,int64,0,Total count of digits (numbers) in the URL.
19,DegitRatioInURL,float64,0.0,Ratio of digits in the URL.
20,NoOfEqualsInURL,int64,0,Count of '=' signs (used in query parameters).
21,NoOfQMarkInURL,int64,0,Count of '?' signs (starts query string).
22,NoOfAmpersandInURL,int64,0,Count of '&' signs (separates parameters).
23,NoOfOtherSpecialCharsInURL,int64,1,Count of other special characters.
24,SpacialCharRatioInURL,float64,0.032,Ratio of special characters in the URL.
25,IsHTTPS,int64,1,Indicates if HTTPS protocol is used (0/1).
26,LineOfCode,int64,558,Total lines of code in the webpage source.
27,LargestLineLength,int64,9381,Length of the longest line of code.
28,HasTitle,int64,1,Checks if the webpage has a title tag (0/1).
29,Title,object,à¸‚à¹ˆà¸²à¸§à¸ªà¸” à¸‚à¹ˆà¸²à¸§à¸§à¸±à¸™à¸™à¸µ...,The text content of the page title.
30,DomainTitleMatchScore,float64,0.0,Match score between domain name and page title.
31,URLTitleMatchScore,float64,0.0,Match score between URL and page title.
32,HasFavicon,int64,0,Checks if the site has a favicon (0/1).
33,Robots,int64,1,Checks for the existence of robots.txt (0/1).
34,IsResponsive,int64,1,Checks if the page is mobile responsive (0/1).
35,NoOfURLRedirect,int64,0,Number of URL redirects.
36,NoOfSelfRedirect,int64,0,Number of redirects to the same page.
37,HasDescription,int64,0,Checks if a meta description exists (0/1).
38,NoOfPopup,int64,0,Number of pop-up windows on the page.
39,NoOfiFrame,int64,1,Number of iFrames used on the page.
40,HasExternalFormSubmit,int64,0,Checks if forms submit to external domains (0/1).
41,HasSocialNet,int64,0,Checks for links to social media networks (0/1).
42,HasSubmitButton,int64,1,Checks for the presence of a submit button (0/1).
43,HasHiddenFields,int64,1,Checks for hidden fields in forms (0/1).
44,HasPasswordField,int64,0,Checks for password input fields (0/1).
45,Bank,int64,1,Checks for banking-related keywords/content (0...
46,Pay,int64,0,Checks for payment-related keywords/content (0...
47,Crypto,int64,0,Checks for crypto-related keywords/content (0/1).
48,HasCopyrightInfo,int64,1,Checks for copyright information (0/1).
49,NoOfImage,int64,34,Total number of images on the webpage.
50,NoOfCSS,int64,20,Total number of CSS files linked.
51,NoOfJS,int64,28,Total number of JavaScript files linked.
52,NoOfSelfRef,int64,119,Number of links pointing to the same domain.
53,NoOfEmptyRef,int64,0,"Number of empty links (e.g., href='#')."
54,NoOfExternalRef,int64,124,Number of links pointing to external domains.
55,label,int64,1,"Target Variable (0: Phishing, 1: Legitimate)"

In [86]:
display(df.head())

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 56 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   FILENAME                    235795 non-null  object
 1   URL                         235795 non-null  object
 2   URLLength                   235795 non-null  int64
 3   Domain                      235795 non-null  object
 4   DomainLength                235795 non-null  int64
 5   IsDomainIP                  235795 non-null  int64
 6   TLD                         235795 non-null  object
 7   URLSimilarityIndex          235795 non-null  float64
 8   CharContinuationRate        235795 non-null  float64
 9   TLDLegitimateProb           235795 non-null  float64
 10  URLCharProb                 235795 non-null  float64
 11  TLDLength                   235795 non-null  int64
 12  NoOfSubDomain               235795 non-null  int64
 13  HasObfuscation              235795 non-null  int64
 14  NoOfObfuscatedChar          235795 non-null  int64
 15  ObfuscationRatio            235795 non-null  float64
 16  NoOfLettersInURL            235795 non-null  int64
 17  LetterRatioInURL            235795 non-null  float64
 18  NoOfDegitsInURL             235795 non-null  int64
 19  DegitRatioInURL             235795 non-null  float64
 20  NoOfEqualsInURL             235795 non-null  int64
 21  NoOfQMarkInURL              235795 non-null  int64
 22  NoOfAmpersandInURL          235795 non-null  int64
 23  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 24  SpacialCharRatioInURL       235795 non-null  float64
 25  IsHTTPS                     235795 non-null  int64
 26  LineOfCode                  235795 non-null  int64
 27  LargestLineLength           235795 non-null  int64
 28  HasTitle                    235795 non-null  int64
 29  Title                       235795 non-null  object
 30  DomainTitleMatchScore       235795 non-null  float64
 31  URLTitleMatchScore          235795 non-null  float64
 32  HasFavicon                  235795 non-null  int64
 33  Robots                      235795 non-null  int64
 34  IsResponsive                235795 non-null  int64
 35  NoOfURLRedirect             235795 non-null  int64
 36  NoOfSelfRedirect            235795 non-null  int64
 37  HasDescription              235795 non-null  int64
 38  NoOfPopup                   235795 non-null  int64
 39  NoOfiFrame                  235795 non-null  int64
 40  HasExternalFormSubmit       235795 non-null  int64
 41  HasSocialNet                235795 non-null  int64
 42  HasSubmitButton             235795 non-null  int64
 43  HasHiddenFields             235795 non-null  int64
 44  HasPasswordField            235795 non-null  int64
 45  Bank                        235795 non-null  int64
 46  Pay                         235795 non-null  int64
 47  Crypto                      235795 non-null  int64
 48  HasCopyrightInfo            235795 non-null  int64
 49  NoOfImage                   235795 non-null  int64
 50  NoOfCSS                     235795 non-null  int64
 51  NoOfJS                      235795 non-null  int64
 52  NoOfSelfRef                 235795 non-null  int64
 53  NoOfEmptyRef                235795 non-null  int64
 54  NoOfExternalRef             235795 non-null  int64
 55  label                       235795 non-null  int64
dtypes: float64(10), int64(41), object(5)
memory usage: 100.7+ MB

In [88]:
display(df.describe().T)

,count,mean,std,min,25%,50%,75%,max
URLLength,235795.0,34.573095,41.314153,13.000000,23.000000,27.000000,34.000000,6.097000e+03
DomainLength,235795.0,21.470396,9.150793,4.000000,16.000000,20.000000,24.000000,1.100000e+02
IsDomainIP,235795.0,0.002706,0.051946,0.000000,0.000000,0.000000,0.000000,1.000000e+00
URLSimilarityIndex,235795.0,78.430778,28.976055,0.155574,57.024793,100.000000,100.000000,1.000000e+02
CharContinuationRate,235795.0,0.845508,0.216632,0.000000,0.680000,1.000000,1.000000,1.000000e+00
TLDLegitimateProb,235795.0,0.260423,0.251628,0.000000,0.005977,0.079963,0.522907,5.229071e-01
URLCharProb,235795.0,0.055747,0.010587,0.001083,0.050747,0.057970,0.062875,9.082366e-02
TLDLength,235795.0,2.764456,0.599739,2.000000,2.000000,3.000000,3.000000,1.300000e+01
NoOfSubDomain,235795.0,1.164758,0.600969,0.000000,1.000000,1.000000,1.000000,1.000000e+01
HasObfuscation,235795.0,0.002057,0.045306,0.000000,0.000000,0.000000,0.000000,1.000000e+00
NoOfObfuscatedChar,235795.0,0.024861,1.876249,0.000000,0.000000,0.000000,0.000000,4.470000e+02
ObfuscationRatio,235795.0,0.000138,0.003817,0.000000,0.000000,0.000000,0.000000,3.480000e-01
NoOfLettersInURL,235795.0,19.428919,29.090330,0.000000,10.000000,14.000000,20.000000,5.191000e+03
LetterRatioInURL,235795.0,0.515946,0.123315,0.000000,0.435000,0.519000,0.594000,9.260000e-01
NoOfDegitsInURL,235795.0,1.881011,11.886695,0.000000,0.000000,0.000000,0.000000,2.011000e+03
DegitRatioInURL,235795.0,0.028616,0.070897,0.000000,0.000000,0.000000,0.000000,6.840000e-01
NoOfEqualsInURL,235795.0,0.062241,0.934704,0.000000,0.000000,0.000000,0.000000,1.760000e+02
NoOfQMarkInURL,235795.0,0.029403,0.193505,0.000000,0.000000,0.000000,0.000000,4.000000e+00
NoOfAmpersandInURL,235795.0,0.025056,0.836448,0.000000,0.000000,0.000000,0.000000,1.490000e+02
NoOfOtherSpecialCharsInURL,235795.0,2.340198,3.527603,0.000000,1.000000,1.000000,3.000000,4.990000e+02
SpacialCharRatioInURL,235795.0,0.063309,0.032393,0.000000,0.038000,0.050000,0.083000,3.970000e-01
IsHTTPS,235795.0,0.782625,0.412461,0.000000,1.000000,1.000000,1.000000,1.000000e+00
LineOfCode,235795.0,1141.900443,3419.950513,2.000000,18.000000,429.000000,1277.000000,4.426660e+05
LargestLineLength,235795.0,12789.532624,152201.099228,22.000000,200.000000,1090.000000,8047.000000,1.397573e+07
HasTitle,235795.0,0.861261,0.345675,0.000000,1.000000,1.000000,1.000000,1.000000e+00
DomainTitleMatchScore,235795.0,50.131427,49.676981,0.000000,0.000000,75.000000,100.000000,1.000000e+02
URLTitleMatchScore,235795.0,52.122098,49.600564,0.000000,0.000000,100.000000,100.000000,1.000000e+02
HasFavicon,235795.0,0.361768,0.480513,0.000000,0.000000,0.000000,1.000000,1.000000e+00
Robots,235795.0,0.266541,0.442151,0.000000,0.000000,0.000000,1.000000,1.000000e+00
IsResponsive,235795.0,0.624513,0.484249,0.000000,0.000000,1.000000,1.000000,1.000000e+00
NoOfURLRedirect,235795.0,0.133438,0.340048,0.000000,0.000000,0.000000,0.000000,1.000000e+00
NoOfSelfRedirect,235795.0,0.040107,0.196210,0.000000,0.000000,0.000000,0.000000,1.000000e+00
HasDescription,235795.0,0.440183,0.496410,0.000000,0.000000,0.000000,1.000000,1.000000e+00
NoOfPopup,235795.0,0.221765,3.870540,0.000000,0.000000,0.000000,0.000000,6.020000e+02
NoOfiFrame,235795.0,1.588638,5.762561,0.000000,0.000000,0.000000,1.000000,1.602000e+03
HasExternalFormSubmit,235795.0,0.043987,0.205067,0.000000,0.000000,0.000000,0.000000,1.000000e+00
HasSocialNet,235795.0,0.456570,0.498111,0.000000,0.000000,0.000000,1.000000,1.000000e+00
HasSubmitButton,235795.0,0.414301,0.492602,0.000000,0.000000,0.000000,1.000000,1.000000e+00
HasHiddenFields,235795.0,0.377799,0.484838,0.000000,0.000000,0.000000,1.000000,1.000000e+00
HasPasswordField,235795.0,0.102263,0.302994,0.000000,0.000000,0.000000,0.000000,1.000000e+00
Bank,235795.0,0.127089,0.333074,0.000000,0.000000,0.000000,0.000000,1.000000e+00
Pay,235795.0,0.237007,0.425247,0.000000,0.000000,0.000000,0.000000,1.000000e+00
Crypto,235795.0,0.023474,0.151403,0.000000,0.000000,0.000000,0.000000,1.000000e+00
HasCopyrightInfo,235795.0,0.486775,0.499826,0.000000,0.000000,0.000000,1.000000,1.000000e+00
NoOfImage,235795.0,26.075689,79.411815,0.000000,0.000000,8.000000,29.000000,8.956000e+03
NoOfCSS,235795.0,6.333111,74.866296,0.000000,0.000000,2.000000,8.000000,3.582000e+04
NoOfJS,235795.0,10.522305,22.312192,0.000000,0.000000,6.000000,15.000000,6.957000e+03
NoOfSelfRef,235795.0,65.071113,176.687539,0.000000,0.000000,12.000000,88.000000,2.739700e+04
NoOfEmptyRef,235795.0,2.377629,17.641097,0.000000,0.000000,0.000000,1.000000,4.887000e+03
NoOfExternalRef,235795.0,49.262516,161.027430,0.000000,1.000000,10.000000,57.000000,2.751600e+04
label,235795.0,0.571895,0.494805,0.000000,0.000000,1.000000,1.000000,1.000000e+00

-134,850 legitimate URL
-100,945 phising URL
-Total 235,795 URL
-54 feature